import Link from "next/link";
import { CITY_CATALOG_SIZE } from "@/data/cities";
import { InfoFooter, InfoHeader } from "@/components/info-chrome";
import { CityLocator } from "@/components/city-locator";
import { cities } from "@/data/cities";

export const metadata = { title: "Cómo funciona | Life Match Argentina", description: "Conocé cómo Life Match convierte tus prioridades en una shortlist explicable de ciudades argentinas." };

export default function HowItWorksPage() {
  const anchorCity = cities.find((city) => city.id === "mendoza") ?? cities[0];
  return <main className="info-page" id="main-content"><InfoHeader />
    <section className="info-hero"><p className="eyebrow">CÓMO FUNCIONA</p><h1>De “quiero otra vida” a 5 ciudades para investigar.</h1><p>Life Match es una herramienta de exploración. Ordena preferencias, presupuesto y forma de moverte; después los cruza con datos comparables de {CITY_CATALOG_SIZE} ciudades argentinas.</p><Link className="button button--primary button--large" href="/">Crear mi mapa</Link><small>45 segundos · sin cuenta · texto opcional</small></section>
    <section className="info-steps"><article><span>01</span><h2>Contás qué necesitás</h2><p>Elegís momento de mudanza, trabajo, presupuesto, hogar, movilidad y hasta 4 prioridades. Podés describir un buen día o seguir sólo con opciones rápidas.</p></article><article><span>02</span><h2>Confirmás la lectura</h2><p>Si escribís texto, el sistema extrae únicamente preferencias explícitas. Vos decidís cuáles conservar. El texto se procesa y se descarta.</p></article><article><span>03</span><h2>Comparamos señales</h2><p>Un motor determinístico pondera costo, conectividad, clima, servicios, movilidad, naturaleza, cultura, caminabilidad y tranquilidad.</p></article><article><span>04</span><h2>Recibís una shortlist</h2><p>Ves top 3 inmediato y 5 opciones en total, con razones, renuncias, confianza, fecha y fuentes para seguir investigando.</p></article></section>
    <section className="service-contract"><div><p className="eyebrow">LO QUE RECIBÍS</p><h2>Un punto de partida explicable.</h2></div><ul><li>5 ciudades ordenadas según tu perfil.</li><li>Razones concretas detrás de cada match.</li><li>Trade-offs que conviene investigar.</li><li>Comparación de hasta 3 ciudades.</li><li>Fuentes, fecha y confianza del dato.</li></ul></section>
    {anchorCity && <section className="territory-card"><div><p className="eyebrow">24 CIUDADES · INFINITAS PREGUNTAS</p><h2>Todo el país entra en conversación.</h2><p>Capitales y ciudades clave, de la Puna a la Patagonia, comparadas con el mismo criterio y sus límites visibles.</p></div><CityLocator city={anchorCity}/></section>}
    <section className="not-a-promise"><p className="eyebrow">LO QUE NO PROMETEMOS</p><h2>No adivinamos dónde vas a ser feliz.</h2><p>No garantizamos alquileres futuros, seguridad, calidad domiciliaria de internet, empleo ni satisfacción. El porcentaje no es una probabilidad: indica ajuste relativo dentro del universo evaluado.</p><Link href="/fuentes">Ver fuentes y límites →</Link></section>
    <section className="faq"><p className="eyebrow">PREGUNTAS FRECUENTES</p><h2>Antes de crear tu mapa</h2><details><summary>¿Necesito registrarme?</summary><p>No. Obtenés resultados completos sin email. Una cuenta será opcional para sincronizar favoritos entre dispositivos.</p></details><details><summary>¿La IA decide el ranking?</summary><p>No. El ranking usa reglas versionadas y reproducibles. El texto opcional sólo ayuda a estructurar preferencias que después confirmás.</p></details><details><summary>¿Cómo entra una ciudad nueva?</summary><p>Necesita ID territorial estable, nueve factores completos, fuentes publicadas y revisión de datos antes de entrar al snapshot.</p></details><details><summary>¿Qué hago con el resultado?</summary><p>Elegí 2 o 3 opciones, revisá sus fuentes, hablá con residentes y visitá antes de tomar una decisión de mudanza.</p></details></section>
    <section className="info-final-cta"><p className="eyebrow">TU PRÓXIMO PASO</p><h2>Armá una shortlist que puedas discutir.</h2><Link className="button button--primary button--large" href="/">Descubrir mis ciudades</Link></section><InfoFooter />
  </main>;
}
